### ISSUE TITLE
[BUG] Working App Broke In prod, Youtube Changed Something

### ISSUE THREAD

**Issue by Rtilwanipsm** [sarbagyastha/youtube_player_flutter#1084]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package

youtube_player_iframe (Default)

### What happened?

Suddenly all my users started reporting this morning that none of the videos are playing. 
I get this error when running my app. 
E/JSBridgeInterface( 8005): error, Exception: type 'int' is not a subtype of type 'String'
I/chromium( 8005): [INFO:CONSOLE:1] "Uncaught (in promise) Error: error, Exception: type 'int' is not a subtype of type 'String'", source: https://www.youtube.com/ (1)

I have not made any changes to the app for months. It was all working well. Maybe some changes on YT side. 

### What is the expected behaviour?

The app was all working fine. This error never came. 

### How to reproduce?

I am on latest version of the plugin. 

### Flutter Doctor Output

```shell

```

**Comment by lvxduck** [comment]
I'm facing the same issue and got a bit of a heart attack.

**Comment by Rtilwanipsm** [comment]
If anyone finds any solution please post it here. I am also trying a few things. If something works out, I will update here.

**Comment by mpsdarkness** [comment]
I'm experiencing a similar issue — everything was working fine yesterday. It seems like YouTube just updated something!

**Comment by xaviertansde** [comment]
Same happens here.

**Comment by SkyairOnline** [comment]
Same happen here too

**Comment by Segatti** [comment]
Guys, if you want a temporary solution, use youtube_player_iframe: ^5.2.1, just while an update comes out, it worked here, but I had to remove some functions from my custom menu

**Comment by Rtilwanipsm** [comment]
@sarbagyastha i know you might be occupied, but it would really mean a lot if you can take out time for this. 

Some of core features have come to stand still because of this overnight issue, I feel YT changed something.

**Comment by Rtilwanipsm** [comment]
> Guys, if you want a temporary solution, use youtube_player_iframe: ^5.2.1, just while an update comes out, it worked here, but I had to remove some functions from my custom menu

@Segatti

did you remove youtube_flutter_player completely and moved to youtube_player_iframe: ^5.2.1?
or is it just a suggestion. 
It might take me months to move completely to youtube_player_iframe

**Comment by kittipongnvj** [comment]
When I debug at 
 
youtube_player_fultter-9.1.1/lib/src/player/raw_youtube_player.dart

`    
..addJavaScriptHandler(
              handlerName: 'Errors',
              callback: (args) {
                controller!.updateValue(
                  controller!.value.copyWith(errorCode: int.parse(args.first)),
                );
              },
            )
`

and change to


`    
..addJavaScriptHandler(
              handlerName: 'Errors',
              callback: (args) {
print(`error is ${arg.first}`)
              },
            )
`

it show error code = 152 when I google it and ask AI and it not show any useful result

**Comment by leehaeillee** [comment]
아래와 같은 로그를 발견했습니다.

`debug_error: {"errorCode":"embedder.identity.denied","errorDetail":"0","errorMessage":"이 동영상은 볼 수 없습니다.","v9":"오류 코드: 0","RD":"0;a6s.0","U6":2,"cpn":"BolS0P3QSjgY4Cbe"},`

**Comment by congdanh1608** [comment]
> I'm facing the same issue, many users of my are reporting and its serious issue here, I can't use youtube_player_iframe doesn't support live video in my app, needs a solution, please guide

It is urgent issue for all production app.

**Comment by congdanh1608** [comment]
https://github.com/sarbagyastha/youtube_player_flutter/pull/1086#issue-3295331213

That is fixed on me

**Comment by GBurg** [comment]
> Guys, if you want a temporary solution, use youtube_player_iframe: ^5.2.1, just while an update comes out, it worked here, but I had to remove some functions from my custom menu

I only use the youtube_player_iframe, and overnight the youtube videos also don't load for me. 

Relevant errors in Debug Console:

> I/chromium(14336): [INFO:CONSOLE:117] "Uncaught TypeError: Cannot read properties of undefined (reading 'setSize')", source: https://www.youtube.com/ (117)
> I/chromium(14336): [INFO:CONSOLE:187] "Unrecognized feature: 'web-share'.", source: https://www.youtube.com/s/player/cbd59245/www-widgetapi.vflset/www-widgetapi.js (187)

I do use the YoutubePlayer of the youtube_player_iframe in my code.

**Comment by Rtilwanipsm** [comment]
This worked for me. 
----------
https://github.com/sarbagyastha/youtube_player_flutter/pull/1086#issue-3295331213
Thanks @nhapham99

That is fixed for me

Here is my temporary hotfix untile new above PR merged

youtube_player_flutter:
git:
url: https://github.com/congdanh1608/youtube_player_flutter.git
path: packages/youtube_player_flutter
--------
Thanks @nhapham99 and @congdanh1608

**Comment by lvxduck** [comment]
It seems that some videos with embedding disabled by the owner are no longer playable.
You can test it using this link: youtube.com/embed/[video_id].

**Comment by congdanh1608** [comment]
> Thanks [@nhapham99](https://github.com/nhapham99) and [@congdanh1608](https://github.com/congdanh1608)! However, it seems that some videos with embedding disabled by the owner are no longer playable. You can test this using the following link: youtube.com/embed/[video_id].

Yes, right. 
I think we cannot play the YouTube private or restricted videos. It may affect the app's release on the Google Play.

**Comment by Dhirenvinay** [comment]
use this as dependency
```

  youtube_player_flutter: 
    git:
      url: https://github.com/Dhirenvinay/youtube_player_flutter.git
      path: packages/youtube_player_flutter
```

**Comment by taodzh** [comment]
This should be an issue returned by the api interface. The data was not sent in the format agreed upon by the app, which led to the app being unable to play the video.
If the released version of the app is to resume playback, the interface return value needs to be modified.

**Comment by sarbagyastha** [comment]
Fixed by https://github.com/sarbagyastha/youtube_player_flutter/pull/1086

**Comment by kcs-govindtank** [comment]
I think on Youtube side some rollbacks or code changes are done to fix the issue, the build with library version 9.1.1 is working now fine without any errors which had issues yesterday in my published build.

**Comment by jithin-kwicklab** [comment]
use https://www.youtube-nocookie.com/

**Comment by amitAarvy** [comment]
> > Guys, if you want a temporary solution, use youtube_player_iframe: ^5.2.1, just while an update comes out, it worked here, but I had to remove some functions from my custom menu
> 
> For whome it is useful: I had the same issue, while I only use the youtube_player_iframe, I updated from youtube_player_iframe 4.0.4 to 5.2.1 and removed this old fix in the pubspec.yaml:
> 
> ```
> dependency_overrides:
>   webview_flutter_wkwebview : 3.18.3
> ```
> 
> But without this old webview_flutter_wkwebview override, 5.2.1 doesn't work, and I get errors like:
> 
> ```
> I/chromium(22965): [INFO:CONSOLE:114] "Uncaught TypeError: Cannot read properties of undefined (reading 'setSize')", source: https://www.youtube.com/ (114)
> I/chromium(22965): [INFO:CONSOLE:187] "Unrecognized feature: 'web-share'.", source: https://www.youtube.com/s/player/cbd59245/www-widgetapi.vflset/www-widgetapi.js (187)
> ```
> 
> However, youtube_player_iframe will first also send the error code 152 already reported above. So every video starts with an Error. According to the Youtube docs, the error 152 is not mentioned:
> 
> https://developers.google.com/youtube/iframe_api_reference#Events
> 
> However, there is a 153 error (not caught in the YoutubeErrors) which is:
> 
> > 153 The request does not include the HTTP Referer header or equivalent API Client identification.
> 
> So it is likely that 152 is also some kind of incorrect request of sorts

I'm facing the same issue, latest version youtube_player_iframe: ^5.2.2 did not fix issue


Cannot read properties of undefined (reading 'setSize')", source: https://www.youtube.com/ (117)

**Comment by DataWhisperer10** [comment]
currently using youtube_player_iframe (version 5.2.2). YouTube settings icon is not accessible
